### ISSUE TITLE
UTF8 support

### ISSUE THREAD

**Issue by FrancoisGallard** [OneraHub/XDSMjs#2]
Hello,

It would be great to have UTF8 support in variable names, since greek symbols like λ are used a lot in MDO. When I put such a symbol in a xdsm.json, the rendering fails. What do you think we should do to make this work?

Thanks
François

**Comment by relf** [comment]
Hi François. Indeed it was not meant to be used with unicode characters. The problem comes from name parsing to handle sub and super script. 
I think I can make it work if unicode characters are specified as HTML numeric references in the json (e.g. <code>&amp;#x03BB;</code> for &#x03BB;).

**Comment by FrancoisGallard** [comment]
Hi Rémi,
That would be perfect I think!
Thanks
Francois

**Comment by FrancoisGallard** [comment]
He Rémi,
Thanks a lot for your commit. That was fast!
I see its working well in the main frame, but the plain numeric code appears in the design space and optimization problem.
Have a nice day
François

**Comment by relf** [comment]
Indeed I forgot about the optimization problem. Do you have a simple json sample you can share?

**Comment by FrancoisGallard** [comment]
I just took one of the examples and replaced all occurences of a variable by "&#955;" (ie the code for Lambda) in the xdsm.json

**Comment by FrancoisGallard** [comment]
It works !
Thanks a lot Rémi, that was fast. 
Have a nice day.
François
