### ISSUE TITLE
Fit the svg into a div

### ISSUE THREAD

**Issue by mdelozzo** [OneraHub/XDSMjs#21]
Hello,

I'm working at IRT on GEMSEO and I would like to display the XDSMjs in a Sphinx Gallery (see [this draft MR](https://gitlab.com/gemseo/dev/gemseo/-/merge_requests/526) on the gemseo repo). I proposed a class `XDSMView` instantiated from a XDSM _json_ file. This object has a `_repr_html_` method so that [Sphinx Gallery](https://sphinx-gallery.github.io/stable/index.html) and Jupyter Notebook can display the XDSM. This looks like:
```python
    def _repr_html_(self) -> str:
        return (
            f"{self.__XDSM_TEMPLATE.format(self.__json_xdsm)}"
            "<div class='xdsm-toolbar'></div>"
            "<div class='xdsm2'></div>"
        )
```

However, a part of the XDSM is hidden as you can see on this screenshot:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/53711375/217895015-f9b82672-043f-419b-b45c-4034abe8d209.png">

From what I understand by digging on the internet, adding a `viewBox` to the `svg` could help (I would need something like ``<svg width="1200" height="400" id="root" viewBox="0 0 1200 400">`` instead of ``<svg width="1200" height="400" id="root">``):

<img width="508" alt="image" src="https://user-images.githubusercontent.com/53711375/217900564-7d5a2f59-1538-4a90-bfed-3d4f85219f98.png">

Are you agree with that? It so, would it be possible to add it? Otherwise, have you got some ideas to force the svg to fit the parent div?

**Comment by relf** [comment]
Hi Matthias. 

I've made the PR #22  with what you suggest. Maybe you could download the `dist/xdsm.js` and check if it fixes your problem?

**Comment by mdelozzo** [comment]
Hi Rémi,
Thanks for your quick answer and PR, it works perfectly!
I also checked with BiLevel formulation and the result is nice!
![image](https://user-images.githubusercontent.com/53711375/218130742-900431f7-1898-436e-8430-4abc5705ef4b.png)
